### ISSUE TITLE
React - Table component - onClick (or other similar props) for rows

### ISSUE THREAD

**Issue by ofreyssinet-ledger** [LedgerHQ/ui#100]
With the `Table` component it is not straightforward to **add a prop to entire rows** (e.g `onClick`)  as we would have to add this prop to the renderer of each column as a workaround.
On top of that, with this workaround, if there is a `columnGap` set, the onClick wouldn't be called if a click happens between two consecutive cells of a same row.

**PS**: I'm creating this issue, following @jelbaz-ledger 's advice, as he told me it could be good if we take the habit of creating issues here in case we encounter an issue while trying to integrate one of this lib's components somewhere and if we're not sure how / don't have time right away to solve it by ourselves.
That way everyone can see it and it doesn't get lost in a slack conversation.

**Comment by jelbaz-ledger** [comment]
Closing since the fix has been released now 📦

**Comment by ofreyssinet-ledger** [comment]
Thanks Julien, sorry I forgot to review this PR in time

**Comment by jelbaz-ledger** [comment]
No worries 😄
